// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: proto/backup.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_proto_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type BackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_proto_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_proto_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_proto_backup_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_backup_proto protoreflect.FileDescriptor

const file_proto_backup_proto_rawDesc = "" +
	"\n" +
	"\x12proto/backup.proto\x12\x06backup\"+\n" +
	"\rBackupRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"(\n" +
	"\x0eBackupResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"*\n" +
	"\x0eProgressUpdate\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8e\x01\n" +
	"\rBackupService\x12:\n" +
	"\tRunBackup\x12\x15.backup.BackupRequest\x1a\x16.backup.BackupResponse\x12A\n" +
	"\x0eStreamProgress\x12\x15.backup.BackupRequest\x1a\x16.backup.ProgressUpdate0\x01B&Z$github.com/iShinzoo/BackUpData/protob\x06proto3"

var (
	file_proto_backup_proto_rawDescOnce sync.Once
	file_proto_backup_proto_rawDescData []byte
)

func file_proto_backup_proto_rawDescGZIP() []byte {
	file_proto_backup_proto_rawDescOnce.Do(func() {
		file_proto_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backup_proto_rawDesc), len(file_proto_backup_proto_rawDesc)))
	})
	return file_proto_backup_proto_rawDescData
}

var file_proto_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_backup_proto_goTypes = []any{
	(*BackupRequest)(nil),  // 0: backup.BackupRequest
	(*BackupResponse)(nil), // 1: backup.BackupResponse
	(*ProgressUpdate)(nil), // 2: backup.ProgressUpdate
}
var file_proto_backup_proto_depIdxs = []int32{
	0, // 0: backup.BackupService.RunBackup:input_type -> backup.BackupRequest
	0, // 1: backup.BackupService.StreamProgress:input_type -> backup.BackupRequest
	1, // 2: backup.BackupService.RunBackup:output_type -> backup.BackupResponse
	2, // 3: backup.BackupService.StreamProgress:output_type -> backup.ProgressUpdate
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_backup_proto_init() }
func file_proto_backup_proto_init() {
	if File_proto_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backup_proto_rawDesc), len(file_proto_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backup_proto_goTypes,
		DependencyIndexes: file_proto_backup_proto_depIdxs,
		MessageInfos:      file_proto_backup_proto_msgTypes,
	}.Build()
	File_proto_backup_proto = out.File
	file_proto_backup_proto_goTypes = nil
	file_proto_backup_proto_depIdxs = nil
}
